var yEl=document.getElementById('y');if(yEl){yEl.textContent=new Date().getFullYear();} // año actual en footer
var cartKey='vv_cart';var cart=[]; // clave de almacenamiento y estado del carrito
function loadCart(){try{const data=localStorage.getItem(cartKey);cart=data?JSON.parse(data):[];}catch(e){cart=[];}} // cargar carrito desde localStorage
function saveCart(){localStorage.setItem(cartKey,JSON.stringify(cart));} // guardar carrito en localStorage
function formatPrice(n){return `$${n.toFixed(2)}`;} // formatear precio
function renderCart(){const empty=document.getElementById('carrito-vacio');const content=document.getElementById('carrito-contenido');const list=document.getElementById('carrito-list');const totalEl=document.getElementById('carrito-total');if(!empty||!content||!list||!totalEl){return;}if(!cart.length){empty.style.display='block';content.style.display='none';return;}empty.style.display='none';content.style.display='block';const aggregated={};cart.forEach(item=>{const k=item.name;if(!aggregated[k]) aggregated[k]={...item,qty:0};aggregated[k].qty+=1;});list.innerHTML='';let total=0;Object.values(aggregated).forEach(it=>{total+=it.price*it.qty;const li=document.createElement('li');li.className='cart-item';li.innerHTML=`<span>${it.name} × ${it.qty}</span><span>${formatPrice(it.price*it.qty)}</span><button class="remove" data-name="${it.name}">Quitar</button>`;list.appendChild(li);});totalEl.textContent=formatPrice(total);} // renderizar carrito
function addToCart(name,price){cart.push({name,price});saveCart();renderCart();} // agregar al carrito
function removeFromCart(name){const idx=cart.findIndex(i=>i.name===name);if(idx>-1){cart.splice(idx,1);saveCart();renderCart();}} // quitar del carrito
function bindProductButtons(){const cards=document.querySelectorAll('.products .card');if(!cards.length){return;}cards.forEach(card=>{const nameEl=card.querySelector('h3');const priceEl=card.querySelector('.price');const btn=card.querySelector('.add-to-cart');if(!nameEl||!priceEl||!btn){return;}const name=nameEl.textContent.trim();const priceText=priceEl.textContent.trim().replace('$','');const price=parseFloat(priceText);if(Number.isNaN(price)){return;}btn.addEventListener('click',()=>addToCart(name,price));});} // enlazar botones de productos
function bindCartActions(){const clearBtn=document.getElementById('vaciar-carrito');const list=document.getElementById('carrito-list');if(clearBtn){clearBtn.addEventListener('click',()=>{cart=[];saveCart();renderCart();});}if(list){list.addEventListener('click',(e)=>{const t=e.target;if(t&&t.matches('button.remove')){removeFromCart(t.getAttribute('data-name'));}});}} // acciones del carrito
function bindPayment(){const form=document.getElementById('form-pago');if(!form){return;}form.addEventListener('submit',(e)=>{e.preventDefault();if(!cart.length){alert('Agrega productos al carrito antes de pagar');return;}alert('Pago procesado');cart=[];saveCart();renderCart();form.reset();});} // envío de pago
function enhanceCatalogCards(){const cards=document.querySelectorAll('.products .card');if(!cards.length){return;}cards.forEach(card=>{if(card.querySelector('.info')){return;}const a=card.querySelector('a.image-wrap');const img=card.querySelector('img');let src='';if(a&&a.getAttribute('href')){src=a.getAttribute('href');}else if(img&&img.getAttribute('src')){src=img.getAttribute('src');}const m=src.match(new RegExp('imagen-(\\d+)\\.jpg','i'));const num=m?m[1]:null;const name=num?`Producto ${num}`:'Producto';const price=29.99;const info=document.createElement('div');info.className='info';info.innerHTML=`<h3>${name}</h3><p class="price">$${price.toFixed(2)}</p><button class="btn secondary add-to-cart">Agregar al carrito</button>`;card.appendChild(info);});} // completar info de tarjetas del catálogo
loadCart();enhanceCatalogCards();bindProductButtons();bindCartActions();renderCart();bindPayment(); // inicialización
